# PyTorch

In [3]:
# 나는 쥬피터 노트북으로 했다. → 셀 별로 실행가능하니까
# pip install jupyter ipykernel

# pip install torch numpy 하고 나서 해야지 import 할 것
import torch
import numpy as np

# 버전 확인
print("numpy", np.__version__)
print("torch", torch.__version__)

numpy 1.26.4
torch 2.9.1


In [4]:
data = [[1, 2],[3, 5]]
x_data = torch.tensor(data)

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [6]:
# ---------------------------------------------------------------------------
# RuntimeError                              Traceback (most recent call last)
# Cell In[9], line 2
#       1 np_array = np.array(data)
# ----> 2 x_np = torch.from_numpy(np_array)

# RuntimeError: Numpy is not available

#이런 경우는 넘파이가 상위버전이라 호환이 안돼서 발생한다. / torch.from_numpy()에서 발생

# version downgrade or fix

# pip install "numpy<2
# pip install numpy==1.26.4

In [7]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")
# X_ones는 x_data와 동일한 shape과 datatype을 가진 텐서를 생성한다.

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")
# x_rand는 x_data와 동일한 shape을 가지지만, 데이터 타입은 float로 지정된 랜덤 텐서를 생성한다.

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.2942, 0.0983],
        [0.0765, 0.8305]]) 



shape is a tuple of tensor dimensions. 

In [8]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

ksh_tensor = torch.tensor([[1,2,3],[4,5,6]])

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")
print(f"KSH Tensor: \n {ksh_tensor}")

# tensor의 shape 확인
print(f"Shape of tensor: {ksh_tensor.shape}")
# tensor의 datatype 확인
print(f"Datatype of tensor: {ksh_tensor.dtype}")
# tensor가 위치한 device 확인
print(f"Device tensor is stored on: {ksh_tensor.device}")

Random Tensor: 
 tensor([[0.3937, 0.7287, 0.6666],
        [0.2676, 0.1178, 0.8074]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
KSH Tensor: 
 tensor([[1, 2, 3],
        [4, 5, 6]])
Shape of tensor: torch.Size([2, 3])
Datatype of tensor: torch.int64
Device tensor is stored on: cpu


In [9]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [12]:
def show(tensor):
    print(f"Shape of tensor: {tensor.shape}")
    print(f"Datatype of tensor: {tensor.dtype}")
    print(f"Device tensor is stored on: {tensor.device}")


show(tensor)

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [21]:
# We move our tensor to the current accelerator if available
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())
    ksh_tensor = ksh_tensor.to(torch.accelerator.current_accelerator())

지금 실행 환경에서 쓸 수 있는 accelerator (eg. CUDA GPU)가 있는지 확인하고, 있다면 가져오기. 

<bs>

.to 는 명시적으로 메모리 복사, 주로 CPU - GPU

In [22]:
# Standard numpy-like indexing and slicing
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [23]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

t2 = torch.cat([ksh_tensor,ksh_tensor], dim=0)
print(t2)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]], device='mps:0')


PyTorch에서(텐서)
PyTorch에서는 보통 torch.cat(또는 torch.concat, torch.concatenate)로 “지정한 차원(dim) 방향으로” 텐서를 이어 붙입니다.

예를 들어,

dim=0이면 위/아래(행 방향)로 붙어서 “행 개수”가 늘고

dim=1이면 좌/우(열 방향)로 붙어서 “열 개수”가 늘어나는 느낌이야.

dim=1이라 좌/우로 열이 붙는데 torch.cat[tensor, tensor, tensor]이라 3개가 붙었구나

In [ ]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T # 행렬곱
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3) # 메모리 절약을 위해 미리 할당된 텐서에 결과 저장

# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor # 내적
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(y3)
print(z3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


주피터(=IPython)에서는 셀의 “마지막 표현식(expression)” 결과를 자동으로 화면에 표시

In [ ]:
agg = tensor.sum() # 원소를 모두 더함, 원소 1개짜리 텐서 -> 스칼라 텐서
agg_item = agg.item() # 그 1개의 값을 파이썬 숫자로 변환
print(agg_item, type(agg_item))

Shape of tensor: torch.Size([4, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
12.0 <class 'float'>


In-place 연산자

결과를 피연산자에게 저장하는 연산자

인플레이스 연산을 통해 메모리를 조금 아끼긴 하나, 연산 히스토리가 즉시 사라져서(덮어써서) 미분값(derivatives = gradient) 계산 때 문제가 될 수 있어 사용을 권장하지 않음


딥러닝에서는 손실(loss)을 줄이기 위해 역전파(backprop)를 하는데, 그때 각 텐서 연산의 미분값(derivatives, gradients)을 계산해야 함

In [ ]:
print(f"{tensor} \n")
tensor.add_(5)
# tensor2 = tensor.add(5) 이건 새로운 텐서를 반환하는 것이지만
# tensor.add_(5) 는 tensor 자체를 변경하는 것 (inplace)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


# Tensor to NumPy array

In [41]:
t = torch.ones(2,3)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([[1., 1., 1.],
        [1., 1., 1.]])
n: [[1. 1. 1.]
 [1. 1. 1.]]


In [42]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([[2., 2., 2.],
        [2., 2., 2.]])
n: [[2. 2. 2.]
 [2. 2. 2.]]


# NumPy array to Tensor

In [44]:
n = np.ones(5)
t = torch.from_numpy(n)

In [45]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
